# Generated by Django 3.1.4 on 2021-01-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='imageURL',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
