# Generated by Django 3.1.4 on 2021-01-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_api', '0002_auto_20210112_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateField(blank=True, null=True, verbose_name='Date (YYYY-MM-DD)'),
        ),
    ]
